stages:
  - build

build_pdf:
  stage: build
  script:
    - git submodule update --init --recursive # Fetches and checks out submodule content
    - echo "Running LaTeX build on local runner..."
    - latexmk -pdf -interaction=nonstopmode 
  only:
    - main        # optional: run only on main branch
  when: manual    # job must be triggered manually
