# Define the main target file
MAIN_TARGET = lphys1213.pdf

# List of files needed by the main latexmk job
LATEX_DEPENDENCIES = lphys1213.tex latexmkrc 

# --- Directory Definitions ---
PYTHON_DIR = Python
XP_DIR = Xp
PDFTEX_DIR = Pdftex
TIKZ_DIR  = Tikz

# --- Discover Files Dynamically ---
PYTHON_SCRIPTS := $(wildcard $(PYTHON_DIR)/0*.py)
PYTHON_PDFS := $(patsubst $(PYTHON_DIR)/%.py, $(PYTHON_DIR)/%.pdf, $(PYTHON_SCRIPTS))

XP_FILES := $(wildcard $(XP_DIR)/*.xp)
XP_EEPIC := $(patsubst $(XP_DIR)/%.xp, $(XP_DIR)/%.eepic, $(XP_FILES))

TIKZ_FILES := $(wildcard $(TIKZ_DIR/*.tikz))
SVG_FILES := $(wildcard $(PDFTEX_DIR)/*.svg)
SVG_PDFS := $(patsubst $(PDFTEX_DIR)/%.svg, $(PDFTEX_DIR)/%.pdf, $(SVG_FILES))
SVG_PDF_TEXS := $(patsubst $(PDFTEX_DIR)/%.svg, $(PDFTEX_DIR)/%.pdf_tex, $(SVG_FILES))

# All generated files needed by latexmk
GENERATED_DEPENDENCIES = $(PYTHON_PDFS) $(XP_EEPIC) $(SVG_PDFS) $(SVG_PDF_TEXS)

.PHONY: all clean python xp pdftex

# ----------------------------------------------------
# 1. Main Target: lphys1213.pdf
# ----------------------------------------------------
all: $(MAIN_TARGET)

$(MAIN_TARGET): $(LATEX_DEPENDENCIES) $(GENERATED_DEPENDENCIES) $(TIKZ_FILES)
	@echo "--- Running latexmk on $< ---"
	latexmk

# ----------------------------------------------------
# 2. Python Scripts to PDF (Executes python3 file.py)
# ----------------------------------------------------
python: $(PYTHON_PDFS)

# Pattern rule for Python files: $(PYTHON_DIR)/file.py -> $(PYTHON_DIR)/file.pdf
$(PYTHON_DIR)/%.pdf: $(PYTHON_DIR)/%.py
	@echo "--- Generating PDF from Python script: $< ---"
	cd $(PYTHON_DIR) && python3 $*.py

# ----------------------------------------------------
# 3. Xp Files to eepic (Executes epix file.xp)
# ----------------------------------------------------
xp: $(XP_EEPIC)

# Pattern rule for Xp files: $(XP_DIR)/file.xp -> $(XP_DIR)/file.eepic
$(XP_DIR)/%.eepic: $(XP_DIR)/%.xp
	@echo "--- Generating eepic from Xp file: $< ---"
	cd $(XP_DIR) && epix $(notdir $<)

# ----------------------------------------------------
# 4. SVG Files to PDF and PDF_TEX (Executes Inkscape)
# ----------------------------------------------------
pdftex: $(SVG_PDFS) $(SVG_PDF_TEXS)

# Pattern rule for SVG files (uses Inkscape for export-latex)
$(PDFTEX_DIR)/%.pdf $(PDFTEX_DIR)/%.pdf_tex: $(PDFTEX_DIR)/%.svg
	@echo "--- Generating PDF/PDF_TEX from SVG file: $< using Inkscape ---"
	# Execute all commands in a single shell block
	@cd $(PDFTEX_DIR) && \
	SVG_FILE=$$(basename $<); \
	BASE_NAME=$$(basename $$SVG_FILE .svg); \
	inkscape --export-filename=$$BASE_NAME.pdf \
	--export-latex \
	$$SVG_FILE

# ----------------------------------------------------
# 5. Cleanup
# ----------------------------------------------------
clean:
	@echo "--- Cleaning up built files ---"
	# Remove files generated by latexmk (common TeX build files)
	latexmk -C
	# Remove files generated by the Python scripts
	$(RM) $(PYTHON_PDFS)
	# Remove files generated by epix
	$(RM) $(XP_EEPIC)
	# Remove files generated by Inkscape
	$(RM) $(SVG_PDFS) $(SVG_PDF_TEXS)
	# Remove the main target file
	$(RM) $(MAIN_TARGET)
