# config/project_name.conf
PROJECT_NAME=lphys1213
TITLE=Physique des fluides
COURSECODE=LPHYS1213
COURSETITLE=Physique des fluides
ACADEMICYEAR=2025--2026
AUTHOR=Michel Crucifix; Eric Deleersnijder
SCHOOL=Universit\'e catholique de Louvain
DOCUMENTTYPE=Lecture notes
LANG=fr
CREDITS=5


